// Contenido de la guía «Lengua de Signos Española (LSE): formas y significados».
// Las descripciones son orientativas: compruébalas siempre en vídeo (DILSE, Spread The Sign).
//
// g = lo que se escribe en el texto (glosa), t = nombre completo, h = cómo se hace.

export const LETTERS = [
  { g: 'A', h: 'Puño cerrado con el pulgar estirado pegado al lateral del índice.' },
  { g: 'B', h: 'Mano plana vertical, dedos juntos hacia arriba, pulgar doblado sobre la palma.' },
  { g: 'C', h: 'Mano curvada en forma de C, vista de lado.' },
  { g: 'CH', h: 'Forma C con un pequeño desplazamiento hacia fuera.' },
  { g: 'D', h: 'Índice hacia arriba; corazón, anular y meñique curvados tocando la yema del pulgar.' },
  { g: 'E', h: 'Dedos doblados por las falanges con las yemas apoyadas sobre el pulgar, que cruza la palma.' },
  { g: 'F', h: 'Índice y pulgar unidos por la yema formando un círculo; los otros tres dedos estirados.' },
  { g: 'G', h: 'Índice y pulgar estirados y paralelos, apuntando hacia un lado (mano horizontal).' },
  { g: 'H', h: 'Índice y corazón juntos y estirados en horizontal, con un leve movimiento lateral.' },
  { g: 'I', h: 'Puño con el meñique estirado hacia arriba.' },
  { g: 'J', h: 'Forma de la I; el meñique traza una curva hacia abajo (como una J).' },
  { g: 'K', h: 'Índice hacia arriba, corazón hacia delante y pulgar entre ambos; leve movimiento hacia arriba.' },
  { g: 'L', h: 'Índice hacia arriba y pulgar hacia el lado formando una L.' },
  { g: 'LL', h: 'Forma L con un doble movimiento corto.' },
  { g: 'M', h: 'Índice, corazón y anular hacia abajo, apoyados sobre el pulgar.' },
  { g: 'N', h: 'Índice y corazón hacia abajo, apoyados sobre el pulgar.' },
  { g: 'Ñ', h: 'Forma N con un movimiento oscilante de muñeca.' },
  { g: 'O', h: 'Todas las yemas tocan la del pulgar formando un círculo.' },
  { g: 'P', h: 'Como la K pero apuntando hacia abajo.' },
  { g: 'Q', h: 'Índice y pulgar en gancho apuntando hacia abajo, con giro de muñeca.' },
  { g: 'R', h: 'Índice y corazón estirados y cruzados.' },
  { g: 'RR', h: 'Forma R con un movimiento lateral.' },
  { g: 'S', h: 'Índice doblado en gancho que traza una S en el aire.' },
  { g: 'T', h: 'Índice doblado sobre el pulgar, que asoma hacia arriba.' },
  { g: 'U', h: 'Índice y corazón juntos y estirados hacia arriba.' },
  { g: 'V', h: 'Índice y corazón separados hacia arriba (forma de V).' },
  { g: 'W', h: 'Índice, corazón y anular separados hacia arriba.' },
  { g: 'X', h: 'Índice en gancho que traza una X.' },
  { g: 'Y', h: 'Pulgar y meñique estirados, resto cerrados.' },
  { g: 'Z', h: 'El índice dibuja una Z en el aire.' },
];

export const NUMBERS = [
  { g: '0', h: 'Forma O (yemas unidas en círculo).' },
  { g: '1', h: 'Índice hacia arriba.' },
  { g: '2', h: 'Índice y corazón hacia arriba.' },
  { g: '3', h: 'Pulgar, índice y corazón estirados.' },
  { g: '4', h: 'Cuatro dedos estirados, pulgar doblado.' },
  { g: '5', h: 'Mano abierta con los cinco dedos separados.' },
  { g: '6', h: 'Mano abierta (5) + índice de la otra mano.' },
  { g: '7', h: 'Mano abierta (5) + dos dedos de la otra mano.' },
  { g: '8', h: 'Mano abierta (5) + tres dedos de la otra mano.' },
  { g: '9', h: 'Mano abierta (5) + cuatro dedos de la otra mano.' },
  { g: '10', h: 'Las dos manos abiertas, o forma del 1 con un giro de muñeca (según zona).' },
];

/** Vocabulario por temas. */
export const CATEGORIES = [
  {
    id: 'saludos',
    title: 'Saludos y cortesía',
    note: 'Acompáñalos de expresión facial: una sonrisa en HOLA, cejas levantadas en ¿QUÉ TAL?',
    items: [
      { g: 'HOLA', h: 'Mano abierta, palma hacia fuera, junto a la sien; se aleja de la cabeza o se agita levemente.' },
      { g: 'ADIÓS', h: 'Mano abierta a la altura del hombro que se agita de lado a lado o abre y cierra los dedos.' },
      { g: 'GRACIAS', h: 'Yemas de la mano plana tocan los labios o la barbilla y la mano avanza hacia delante y abajo hacia la persona.' },
      { g: 'DE NADA', h: 'Mano plana, palma hacia arriba, que se aparta hacia fuera.' },
      { g: 'POR FAVOR', h: 'Variante frecuente: manos juntas palma con palma delante del pecho con un leve balanceo (varía mucho por zona).' },
      { g: 'PERDÓN', t: 'PERDÓN / LO SIENTO', h: 'Mano plana o puño sobre el pecho haciendo un círculo, con gesto de disculpa.' },
      { g: 'BIEN', t: 'BUENO / BIEN', h: 'Pulgar hacia arriba con un pequeño avance.' },
      { g: 'MAL', h: 'Pulgar hacia abajo, o mano plana que oscila con gesto de disgusto.' },
      { g: 'BUENOS DÍAS', h: 'BUENO + DÍA (mano abierta que sube desde el lado como el sol saliendo).' },
      { g: 'BUENAS NOCHES', h: 'BUENO + NOCHE (manos planas que bajan y se cruzan delante de la cara, como oscurecer).' },
      { g: '¿QUÉ TAL?', h: 'Manos abiertas, palmas hacia arriba, con un leve movimiento hacia fuera y cejas levantadas.' },
      { g: 'SÍ', h: 'Puño que se mueve arriba y abajo como una cabeza asintiendo, junto con asentir.' },
      { g: 'NO', h: 'Índice estirado que se mueve de lado a lado, junto con negar con la cabeza.' },
      { g: 'ENCANTADO', t: 'ENCANTADO/A', h: 'Mano plana sobre el pecho con una sonrisa, a menudo seguido de señalar a la persona.' },
      { g: 'AYUDA', h: 'Puño con el pulgar arriba apoyado sobre la palma de la otra mano; ambas suben juntas.' },
      { g: 'OTRA VEZ', t: 'OTRA VEZ / REPITE', h: 'Índice y corazón doblados que golpean dos veces la palma de la otra mano.' },
      { g: 'DESPACIO', h: 'Mano plana que acaricia lentamente el dorso de la otra mano, o baja con suavidad.' },
      { g: 'NO ENTIENDO', h: 'NO + ENTENDER (índice junto a la sien que se aleja) con gesto de duda.' },
      { g: 'SORDO', h: 'El índice toca la oreja y luego la boca (o la mano se cierra junto a la oreja).' },
      { g: 'OYENTE', h: 'El índice señala la oreja con un leve movimiento.' },
    ],
  },
  {
    id: 'personas',
    title: 'Pronombres, personas y familia',
    note: 'Los pronombres se hacen señalando y no tienen género. Presentarse: YO NOMBRE + deletreo.',
    items: [
      { g: 'YO', h: 'Índice señala o toca tu propio pecho.' },
      { g: 'TÚ', h: 'Índice señala a la persona con la que hablas.' },
      { g: 'ÉL', t: 'ÉL / ELLA', h: 'Índice señala a la persona o a su punto en el espacio, a un lado.' },
      { g: 'NOSOTROS', h: 'Índice describe un arco desde un hombro al otro pasando por el pecho.' },
      { g: 'VOSOTROS', h: 'Índice describe un arco abarcando a los interlocutores.' },
      { g: 'ELLOS', h: 'Índice describe un arco hacia el lado donde están.' },
      { g: 'MÍO', t: 'MÍO / MI', h: 'Mano plana sobre el pecho.' },
      { g: 'TUYO', t: 'TUYO / TU', h: 'Mano plana o puño dirigido hacia la persona.' },
      { g: 'NOMBRE', h: 'Se usa para presentarse: YO NOMBRE + deletreo (M-A-R-C-O-S).' },
      { g: 'PERSONA', h: 'Manos planas enfrentadas que bajan a la vez delante del cuerpo.' },
      { g: 'HOMBRE', h: 'Signo junto a la barbilla o la cara que alude a la barba (varía).' },
      { g: 'MUJER', h: 'Signo junto a la mejilla o la oreja (pendiente) o a la mejilla (varía).' },
      { g: 'NIÑO', t: 'NIÑO/A', h: 'Mano plana, palma hacia abajo, a la altura de un niño, con leve movimiento.' },
      { g: 'MADRE', t: 'MADRE / MAMÁ', h: 'Índice que roza la mejilla o la barbilla (variantes regionales).' },
      { g: 'PADRE', t: 'PADRE / PAPÁ', h: 'Signo junto al labio superior que alude al bigote (variantes regionales).' },
      { g: 'HERMANO', t: 'HERMANO/A', h: 'Índices estirados que se juntan uno al lado del otro.' },
      { g: 'HIJO', t: 'HIJO/A', h: 'Mano que sale del vientre hacia fuera.' },
      { g: 'ABUELO', t: 'ABUELO/A', h: 'Signo de PADRE / MADRE seguido de un movimiento que indica «mayor».' },
      { g: 'FAMILIA', h: 'Manos en forma F (o C) que describen un círculo delante del cuerpo hasta juntarse.' },
      { g: 'AMIGO', t: 'AMIGO/A', h: 'Manos que se entrelazan o chocan suavemente dos veces.' },
      { g: 'NOVIO', t: 'NOVIO/A', h: 'Ambas manos con índices juntos o dedos entrelazados delante del pecho.' },
      { g: 'BEBÉ', h: 'Brazos cruzados como si acunases, con balanceo.' },
    ],
  },
  {
    id: 'preguntas',
    title: 'Preguntas',
    note: 'Cejas levantadas para preguntas de sí/no y fruncidas para preguntas abiertas. El interrogativo va al final: TÚ NOMBRE QUÉ = ¿Cómo te llamas?',
    items: [
      { g: '¿QUÉ?', h: 'Mano abierta o índice que oscila de lado a lado, palma hacia arriba, cejas fruncidas.' },
      { g: '¿QUIÉN?', h: 'Índice que hace pequeños círculos junto a la boca o la barbilla.' },
      { g: '¿DÓNDE?', h: 'Mano abierta o índice que oscila delante del cuerpo con mirada interrogativa.' },
      { g: '¿CUÁNDO?', h: 'Índice que golpea suavemente la mejilla o se mueve en círculo junto a ella (varía).' },
      { g: '¿CÓMO?', h: 'Manos con los dedos flexionados que giran hacia fuera, palmas hacia arriba.' },
      { g: '¿POR QUÉ?', h: 'Mano que toca la frente y se separa (relación con PENSAR).' },
      { g: '¿CUÁNTO?', h: 'Dedos que se abren y cierran rápidamente (como contando) con cejas fruncidas.' },
      { g: '¿CUÁL?', h: 'Pulgar e índice que alternan apuntando a varias opciones.' },
    ],
  },
  {
    id: 'tiempo',
    title: 'Tiempo',
    note: 'Línea del tiempo: el pasado detrás del hombro, el presente delante del cuerpo y el futuro hacia delante.',
    items: [
      { g: 'HOY', t: 'HOY / AHORA', h: 'Ambas manos planas, palmas arriba, que bajan a la vez delante del cuerpo.' },
      { g: 'AYER', h: 'Pulgar o índice que va hacia atrás por encima del hombro.' },
      { g: 'MAÑANA', t: 'MAÑANA (día siguiente)', h: 'Pulgar o índice que avanza hacia delante desde la mejilla.' },
      { g: 'ANTES', t: 'ANTES / PASADO', h: 'Mano plana que va hacia atrás por encima del hombro.' },
      { g: 'DESPUÉS', t: 'DESPUÉS / FUTURO', h: 'Mano plana que avanza hacia delante.' },
      { g: 'SIEMPRE', h: 'Índice que describe círculos mientras avanza.' },
      { g: 'NUNCA', h: 'Mano que describe una curva y corta hacia abajo con gesto de negación.' },
      { g: 'DÍA', h: 'Mano abierta que sube desde el lado (el sol).' },
      { g: 'SEMANA', h: 'Índice que se desliza sobre la palma de la otra mano.' },
      { g: 'MES', h: 'Índice que baja por el índice de la otra mano. MES + número también sirve (MES 3 = marzo).' },
      { g: 'AÑO', h: 'Puños que giran uno alrededor del otro (la Tierra alrededor del Sol).' },
      { g: 'HORA', h: 'Índice que toca la muñeca (donde va el reloj).' },
      { g: 'TARDE', t: 'TARDE / NOCHE', h: 'Mano que baja como el sol poniéndose; en NOCHE las manos se cruzan delante de la cara.' },
      { g: 'LUNES', h: 'Letra L con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'MARTES', h: 'Letra M con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'MIÉRCOLES', h: 'Letra X con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'JUEVES', h: 'Letra J con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'VIERNES', h: 'Letra V con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'SÁBADO', h: 'Letra S con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'DOMINGO', h: 'Letra D con un pequeño movimiento circular (en muchas zonas).' },
      { g: 'PRIMAVERA', h: 'Dedos que se abren como flores brotando.' },
      { g: 'VERANO', h: 'Mano que se pasa por la frente secando el sudor.' },
      { g: 'OTOÑO', h: 'Mano que cae balanceándose como una hoja.' },
      { g: 'INVIERNO', h: 'Puños temblando junto al cuerpo (frío).' },
    ],
  },
  {
    id: 'verbos',
    title: 'Verbos frecuentes',
    note: 'Los verbos no se conjugan: el tiempo lo marcan signos como AYER o MAÑANA. DAR, AYUDAR o PREGUNTAR cambian de dirección según quién hace la acción. SER / ESTAR normalmente no se signa.',
    items: [
      { g: 'TENER', h: 'Mano abierta que se cierra en puño hacia el pecho (agarrar).' },
      { g: 'QUERER', h: 'Mano en garra que se mueve hacia el pecho o se cierra delante de él.' },
      { g: 'PODER', h: 'Puños o manos que bajan con firmeza a la vez.' },
      { g: 'SABER', h: 'Yemas que tocan la frente o la sien.' },
      { g: 'PENSAR', h: 'Índice que toca la sien con un pequeño giro.' },
      { g: 'ENTENDER', h: 'Índice junto a la sien que se aleja o se estira.' },
      { g: 'OLVIDAR', h: 'Mano junto a la frente que se aparta abriéndose (algo que se escapa).' },
      { g: 'VER', h: 'Índice y corazón en V salen desde los ojos hacia delante.' },
      { g: 'MIRAR', h: 'V que sale de los ojos hacia el objeto mirado.' },
      { g: 'OÍR', t: 'OÍR / ESCUCHAR', h: 'Mano ahuecada junto a la oreja.' },
      { g: 'HABLAR', h: 'Índice que sale de la boca con movimiento repetido hacia delante.' },
      { g: 'DECIR', h: 'Índice que sale de la boca hacia delante una vez.' },
      { g: 'SIGNAR', h: 'Índices que giran alternativamente uno sobre otro delante del pecho.' },
      { g: 'COMER', h: 'Mano en O (o pinza) que se lleva a la boca repetidamente.' },
      { g: 'BEBER', h: 'Mano en C que se lleva a la boca como un vaso.' },
      { g: 'DORMIR', h: 'Mano plana bajo la mejilla inclinando la cabeza, o mano que se cierra delante de los ojos.' },
      { g: 'TRABAJAR', h: 'Puños o manos planas que golpean alternativamente una sobre otra.' },
      { g: 'ESTUDIAR', h: 'Mano que se mueve sobre la palma de la otra (leer de un libro) con repetición.' },
      { g: 'LEER', h: 'V que recorre la palma de la otra mano de arriba abajo.' },
      { g: 'ESCRIBIR', h: 'Pinza que «escribe» sobre la palma de la otra mano.' },
      { g: 'IR', h: 'Índice que se desplaza hacia delante en arco.' },
      { g: 'VENIR', h: 'Índice que viene hacia el cuerpo.' },
      { g: 'ANDAR', t: 'ANDAR / CAMINAR', h: 'Índice y corazón invertidos que «caminan».' },
      { g: 'CORRER', h: 'Puños que se mueven alternativamente como al correr.' },
      { g: 'CONDUCIR', h: 'Puños sujetando un volante imaginario.' },
      { g: 'VIVIR', h: 'Manos planas o en A que suben por el pecho.' },
      { g: 'GUSTAR', h: 'Mano que roza el pecho o la barbilla hacia abajo con gesto agradable.' },
      { g: 'AMAR', t: 'AMAR / QUERER (a alguien)', h: 'Brazos cruzados sobre el pecho (abrazo).' },
      { g: 'NECESITAR', h: 'Índice en gancho que baja con firmeza.' },
      { g: 'BUSCAR', h: 'Mano en C que da vueltas delante de los ojos.' },
      { g: 'ENCONTRAR', h: 'Mano que baja y «pellizca» algo con pinza y lo levanta.' },
      { g: 'COMPRAR', h: 'Mano que saca algo de la palma de la otra hacia fuera (pagar).' },
      { g: 'PAGAR', h: 'Pinza que golpea la palma de la otra y avanza.' },
      { g: 'ESPERAR', h: 'Dedos que tamborilean o mano que se mueve arriba y abajo con paciencia.' },
      { g: 'JUGAR', h: 'Manos en Y que se agitan.' },
      { g: 'DAR', h: 'Manos que se mueven desde el cuerpo hacia quien recibe.' },
      { g: 'AYUDAR', h: 'Puño sobre la palma, ambas se desplazan hacia quien recibe la ayuda.' },
      { g: 'PREGUNTAR', h: 'Índice en gancho que se dirige hacia la persona a quien se pregunta.' },
      { g: 'EMPEZAR', h: 'Índice que gira entre los dedos de la otra mano.' },
      { g: 'TERMINAR', t: 'TERMINAR / ACABAR', h: 'Manos abiertas que giran hacia fuera, o mano plana que corta sobre la otra.' },
    ],
  },
  {
    id: 'emociones',
    title: 'Emociones y estados',
    note: 'La cara es tan importante como la mano. La intensidad se muestra exagerando el movimiento y la expresión.',
    items: [
      { g: 'CONTENTO', t: 'CONTENTO / FELIZ', h: 'Manos planas que suben rozando el pecho repetidamente, con sonrisa.' },
      { g: 'TRISTE', h: 'Mano abierta que baja delante de la cara, con expresión triste.' },
      { g: 'ENFADADO', h: 'Mano en garra delante de la cara o el pecho que se tensa, ceño fruncido.' },
      { g: 'MIEDO', h: 'Manos abiertas que tiemblan delante del pecho, cuerpo hacia atrás.' },
      { g: 'NERVIOSO', h: 'Dedos que tiemblan o manos que se agitan delante del pecho.' },
      { g: 'CANSADO', h: 'Manos sobre el pecho que caen hacia abajo, hombros caídos.' },
      { g: 'ABURRIDO', h: 'Índice que roza la nariz o la mejilla con gesto de desgana.' },
      { g: 'SORPRENDIDO', h: 'Manos que se abren junto a los ojos, cejas muy arriba.' },
      { g: 'TRANQUILO', h: 'Manos planas, palmas abajo, que bajan despacio.' },
      { g: 'PREOCUPADO', h: 'Manos que giran delante de la frente, ceño fruncido.' },
      { g: 'ENAMORADO', h: 'Mano sobre el corazón que late o se aleja.' },
      { g: 'VERGÜENZA', h: 'Mano que sube por la mejilla (sonrojarse).' },
      { g: 'ORGULLOSO', h: 'Pulgar que sube por el pecho, cuerpo erguido.' },
      { g: 'ENFERMO', h: 'Dedo corazón que toca la frente y el estómago a la vez.' },
      { g: 'DOLOR', h: 'Índices que se enfrentan y giran en la zona que duele.' },
      { g: 'HAMBRE', h: 'Mano en C que baja por el pecho o el estómago.' },
      { g: 'SED', h: 'Índice que baja por la garganta.' },
      { g: 'FRÍO', h: 'Puños que tiemblan junto al cuerpo.' },
      { g: 'CALOR', h: 'Mano que se abanica la cara o seca la frente.' },
      { g: 'REGULAR', t: 'REGULAR / ASÍ ASÍ', h: 'Mano plana, palma abajo, que oscila de lado a lado.' },
    ],
  },
  {
    id: 'colores',
    title: 'Colores',
    items: [
      { g: 'COLOR', h: 'Dedos que se mueven delante de la boca o la barbilla.' },
      { g: 'ROJO', h: 'Índice que roza los labios hacia abajo.' },
      { g: 'BLANCO', h: 'Mano que se cierra sobre el pecho o roza la mejilla (varía).' },
      { g: 'NEGRO', h: 'Índice que roza la ceja o el pelo de lado a lado.' },
      { g: 'AZUL', h: 'Mano en forma A o B que gira con la letra inicial.' },
      { g: 'VERDE', h: 'Letra V que gira o se agita.' },
      { g: 'AMARILLO', h: 'Mano que roza la mejilla o letra A con giro.' },
      { g: 'ROSA', h: 'Meñique o yemas que rozan la mejilla.' },
      { g: 'MARRÓN', h: 'Mano que baja por la mejilla.' },
      { g: 'GRIS', h: 'Manos abiertas con dedos que se entrecruzan (mezcla blanco y negro).' },
    ],
  },
  {
    id: 'comida',
    title: 'Comida y bebida',
    items: [
      { g: 'AGUA', h: 'Índice que golpea la barbilla o los labios.' },
      { g: 'PAN', h: 'Mano que corta sobre la otra, como rebanadas.' },
      { g: 'LECHE', h: 'Puños que aprietan alternativamente (ordeñar).' },
      { g: 'CAFÉ', h: 'Puño que gira sobre el otro (molinillo) o mano que remueve una taza.' },
      { g: 'CARNE', h: 'Pinza que pellizca el dorso o la piel de la otra mano.' },
      { g: 'PESCADO', h: 'Mano plana que avanza ondulando como un pez.' },
      { g: 'FRUTA', h: 'Mano en garra que gira junto a la mejilla.' },
      { g: 'MANZANA', h: 'Mano en garra que gira junto a la boca (morder).' },
      { g: 'HUEVO', h: 'Dedos que rompen un huevo imaginario sobre el borde de la otra mano.' },
      { g: 'DESAYUNO', t: 'DESAYUNO / COMIDA / CENA', h: 'Signo COMER combinado con el momento del día.' },
    ],
  },
  {
    id: 'lugares',
    title: 'Lugares y transporte',
    items: [
      { g: 'CASA', h: 'Manos planas que se tocan por las yemas formando un tejado.' },
      { g: 'ESCUELA', t: 'ESCUELA / COLEGIO', h: 'Manos que aplauden o se golpean, una sobre otra.' },
      { g: 'HOSPITAL', h: 'Índice que dibuja una cruz en el brazo.' },
      { g: 'CALLE', h: 'Manos planas paralelas que avanzan.' },
      { g: 'CIUDAD', h: 'Manos en forma de tejado que se repiten en varios puntos.' },
      { g: 'TIENDA', h: 'COMPRAR + CASA, o signo propio local.' },
      { g: 'BAÑO', t: 'BAÑO / ASEO', h: 'Mano en forma de letra W o V que se agita, o gesto de lavarse las manos (varía).' },
      { g: 'COCHE', h: 'Puños sujetando el volante.' },
      { g: 'AUTOBÚS', h: 'Volante grande, con los brazos más abiertos.' },
      { g: 'TREN', h: 'Dedos que se deslizan sobre los dedos de la otra mano (las vías).' },
      { g: 'AVIÓN', h: 'Mano en Y que vuela hacia delante.' },
      { g: 'ESPAÑA', h: 'Signo propio: mano que roza el hombro o el pecho (referencia al traje), varía.' },
      { g: 'MADRID', h: 'Signo propio local (el oso o la M).' },
    ],
  },
  {
    id: 'trabajo',
    title: 'Trabajo y oficina',
    items: [
      { g: 'TRABAJO', h: 'Puños o manos que golpean alternativamente una sobre otra.' },
      { g: 'JEFE', h: 'Mano en garra o en C sobre el hombro, que sube (galones).' },
      { g: 'COMPAÑERO', h: 'Manos que se juntan lado a lado.' },
      { g: 'REUNIÓN', h: 'Manos abiertas con dedos hacia abajo que se juntan en el centro (gente reunida).' },
      { g: 'ORDENADOR', h: 'Dedos que teclean en el aire.' },
      { g: 'TELÉFONO', t: 'TELÉFONO / MÓVIL', h: 'Mano en Y junto a la oreja, o mano que sostiene un móvil.' },
      { g: 'CORREO', t: 'CORREO / EMAIL', h: 'Mano que mete una carta en un buzón, o letra E + enviar.' },
      { g: 'DINERO', h: 'Pulgar que roza las yemas de los dedos.' },
      { g: 'VACACIONES', h: 'Pulgares en las axilas con los dedos abiertos que se mueven.' },
      { g: 'TELETRABAJO', h: 'CASA + TRABAJAR.' },
    ],
  },
];

export const COMMANDS = [
  { g: 'ESPACIO', h: 'Un gesto tuyo para separar palabras. No es un signo de la LSE.' },
  { g: 'BORRAR', h: 'Un gesto tuyo para borrar lo último escrito. No es un signo de la LSE.' },
];

/** Reglas de gramática básica de la guía. */
export const GRAMMAR = [
  ['Orden de la frase', 'Suele ser Sujeto + Objeto + Verbo. «Yo como manzana» → YO MANZANA COMER.'],
  ['Tiempo al principio', 'El marcador temporal abre la frase. «Ayer fui al cine» → AYER YO CINE IR.'],
  ['Lugar antes que la acción', 'Primero se sitúa el escenario y luego lo que pasa.'],
  ['Sin artículos ni preposiciones', '«el», «la», «de», «a» no se signan; la relación la da el espacio.'],
  ['Negación al final', 'El NO o el negar con la cabeza va detrás. «No me gusta» → GUSTAR NO.'],
  ['Plural', 'Repitiendo el signo en varios puntos, añadiendo un número o MUCHOS.'],
  ['Clasificadores', 'Formas de mano que representan un tipo de objeto y se mueven para describir cómo se desplaza o se coloca.'],
  ['Expresión facial gramatical', 'Cejas para preguntas, mejillas infladas para «grande», labios apretados para «pequeño» o «preciso».'],
  ['Labialización', 'Se pronuncia sin voz la palabra española; ayuda a distinguir signos parecidos.'],
];

export const PHRASES = [
  ['¿Cómo te llamas?', 'TÚ NOMBRE QUÉ'],
  ['¿Dónde vives?', 'TÚ VIVIR DÓNDE'],
  ['¿Cuántos años tienes?', 'TÚ EDAD CUÁNTO'],
  ['¿Eres sordo?', 'TÚ SORDO (cejas arriba)'],
  ['¿Puedes repetir?', 'OTRA VEZ PODER (cejas arriba)'],
  ['¿Dónde está el baño?', 'BAÑO DÓNDE'],
];
